services:
  nginx:
    image: nginx:alpine
    platform: linux/arm64/v8  # For local M3 apple silicon
    ports:
      - "80:80"    # Use HTTP port 80 for local development
      - "443:443"  # Keep HTTPS available for testing
    volumes:
      - ./nginx.local.conf:/etc/nginx/nginx.conf:ro
      # Remove SSL certificate volumes for local development

  app-service:
    extra_hosts:
      # or if nginx is in a container:
      - "live-bootcamp.local:host-gateway"  # Special Docker keyword that resolves to host
    build:
      context: ./app-service
    environment:
      TLS_ENABLED: "false"
      AUTH_SERVICE_BASE_URL: "http://live-bootcamp.local/auth"
      BASE_URL: "http://live-bootcamp.local/app"
    ports:
      - "8000:8000"  # Expose for direct access during development
    # Remove certificate volumes for local development
    volumes: []

  auth-service:
    build:
      context: ./auth-service
    environment:
      TLS_ENABLED: "false"
      BASE_URL: "http://live-bootcamp.local/auth"
    ports:
      - "8001:8001"  # Expose for direct access during development
    # Remove certificate volumes for local development
    volumes: []
