services:
  nginx:
    image: nginx:alpine
    restart: "always"
    ports:
      - "80:80"   # HTTP for redirects and health checks
      - "443:443" # HTTPS for production traffic
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy-certs:/etc/nginx/ssl:ro
    depends_on:
      - app-service
      - auth-service
    networks:
      - bootcamp-network

  app-service:
    extra_hosts:
      # or if nginx is in a container:
      - "live-bootcamp.jocax.com:host-gateway"  # Special Docker keyword that resolves to host
    image: dev4ever/rust-bootcamp-app-service # specify name of image on Docker Hub
    restart: "always" # automatically restart container when server crashes
    environment: # set up environment variables
      TLS_ENABLED: "true"  # All services use shared domain certificates
      TLS_CERT_PATH: "/home/deploy/live-bootcamp/certs/fullchain.pem"
      TLS_KEY_PATH: "/home/deploy/live-bootcamp/certs/privkey.pem"
      AUTH_SERVICE_BASE_URL: "https://live-bootcamp.jocax.com/auth"
      BASE_URL: "https://live-bootcamp.jocax.com/app"
    volumes:
      - ./deploy-certs:/home/deploy/live-bootcamp/certs:ro
    depends_on: # only run app-service after auth-service has started
      auth-service:
        condition: service_started
    networks:
      - bootcamp-network
    env_file:
      - .env

  auth-service:
    image: dev4ever/rust-bootcamp-auth-service
    restart: "always" # automatically restart container when server crashes
    environment:
      TLS_ENABLED: "true"  # All services use shared domain certificates
      TLS_CERT_PATH: "/home/deploy/live-bootcamp/certs/fullchain.pem"
      TLS_KEY_PATH: "/home/deploy/live-bootcamp/certs/privkey.pem"
      JWT_SECRET: $JWT_SECRET
      BASE_URL: "https://live-bootcamp.jocax.com/auth"
    volumes:
      - ./deploy-certs:/home/deploy/live-bootcamp/certs:ro
    networks:
      - bootcamp-network
    env_file:
      - .env

networks:
  bootcamp-network:
    driver: bridge

